/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SeedAstrologersRouteImport } from './routes/seed-astrologers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AstrologerLoginRouteImport } from './routes/astrologer-login'
import { Route as AstrologerRouteImport } from './routes/astrologer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AstrologersIndexRouteImport } from './routes/astrologers.index'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as AstrologersIdRouteImport } from './routes/astrologers.$id'
import { Route as CallModeIdRouteImport } from './routes/call.$mode.$id'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedAstrologersRoute = SeedAstrologersRouteImport.update({
  id: '/seed-astrologers',
  path: '/seed-astrologers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologerLoginRoute = AstrologerLoginRouteImport.update({
  id: '/astrologer-login',
  path: '/astrologer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologerRoute = AstrologerRouteImport.update({
  id: '/astrologer',
  path: '/astrologer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologersIndexRoute = AstrologersIndexRouteImport.update({
  id: '/astrologers/',
  path: '/astrologers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatsRoute,
} as any)
const AstrologersIdRoute = AstrologersIdRouteImport.update({
  id: '/astrologers/$id',
  path: '/astrologers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CallModeIdRoute = CallModeIdRouteImport.update({
  id: '/call/$mode/$id',
  path: '/call/$mode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrologer': typeof AstrologerRoute
  '/astrologer-login': typeof AstrologerLoginRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRouteWithChildren
  '/details': typeof DetailsRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/seed-astrologers': typeof SeedAstrologersRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/astrologers/$id': typeof AstrologersIdRoute
  '/chats/$id': typeof ChatsIdRoute
  '/astrologers/': typeof AstrologersIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/call/$mode/$id': typeof CallModeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrologer': typeof AstrologerRoute
  '/astrologer-login': typeof AstrologerLoginRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRouteWithChildren
  '/details': typeof DetailsRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/seed-astrologers': typeof SeedAstrologersRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/astrologers/$id': typeof AstrologersIdRoute
  '/chats/$id': typeof ChatsIdRoute
  '/astrologers': typeof AstrologersIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/call/$mode/$id': typeof CallModeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astrologer': typeof AstrologerRoute
  '/astrologer-login': typeof AstrologerLoginRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/chats': typeof ChatsRouteWithChildren
  '/details': typeof DetailsRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/seed-astrologers': typeof SeedAstrologersRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/astrologers/$id': typeof AstrologersIdRoute
  '/chats/$id': typeof ChatsIdRoute
  '/astrologers/': typeof AstrologersIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/call/$mode/$id': typeof CallModeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astrologer'
    | '/astrologer-login'
    | '/auth'
    | '/categories'
    | '/chats'
    | '/details'
    | '/live'
    | '/onboarding'
    | '/profile'
    | '/seed-astrologers'
    | '/splash'
    | '/store'
    | '/wallet'
    | '/astrologers/$id'
    | '/chats/$id'
    | '/astrologers/'
    | '/api/public/cashfree-webhook'
    | '/call/$mode/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrologer'
    | '/astrologer-login'
    | '/auth'
    | '/categories'
    | '/chats'
    | '/details'
    | '/live'
    | '/onboarding'
    | '/profile'
    | '/seed-astrologers'
    | '/splash'
    | '/store'
    | '/wallet'
    | '/astrologers/$id'
    | '/chats/$id'
    | '/astrologers'
    | '/api/public/cashfree-webhook'
    | '/call/$mode/$id'
  id:
    | '__root__'
    | '/'
    | '/astrologer'
    | '/astrologer-login'
    | '/auth'
    | '/categories'
    | '/chats'
    | '/details'
    | '/live'
    | '/onboarding'
    | '/profile'
    | '/seed-astrologers'
    | '/splash'
    | '/store'
    | '/wallet'
    | '/astrologers/$id'
    | '/chats/$id'
    | '/astrologers/'
    | '/api/public/cashfree-webhook'
    | '/call/$mode/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstrologerRoute: typeof AstrologerRoute
  AstrologerLoginRoute: typeof AstrologerLoginRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  DetailsRoute: typeof DetailsRoute
  LiveRoute: typeof LiveRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SeedAstrologersRoute: typeof SeedAstrologersRoute
  SplashRoute: typeof SplashRoute
  StoreRoute: typeof StoreRoute
  WalletRoute: typeof WalletRoute
  AstrologersIdRoute: typeof AstrologersIdRoute
  AstrologersIndexRoute: typeof AstrologersIndexRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  CallModeIdRoute: typeof CallModeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed-astrologers': {
      id: '/seed-astrologers'
      path: '/seed-astrologers'
      fullPath: '/seed-astrologers'
      preLoaderRoute: typeof SeedAstrologersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologer-login': {
      id: '/astrologer-login'
      path: '/astrologer-login'
      fullPath: '/astrologer-login'
      preLoaderRoute: typeof AstrologerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologer': {
      id: '/astrologer'
      path: '/astrologer'
      fullPath: '/astrologer'
      preLoaderRoute: typeof AstrologerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologers/': {
      id: '/astrologers/'
      path: '/astrologers'
      fullPath: '/astrologers/'
      preLoaderRoute: typeof AstrologersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/astrologers/$id': {
      id: '/astrologers/$id'
      path: '/astrologers/$id'
      fullPath: '/astrologers/$id'
      preLoaderRoute: typeof AstrologersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$mode/$id': {
      id: '/call/$mode/$id'
      path: '/call/$mode/$id'
      fullPath: '/call/$mode/$id'
      preLoaderRoute: typeof CallModeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsIdRoute: typeof ChatsIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIdRoute: ChatsIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstrologerRoute: AstrologerRoute,
  AstrologerLoginRoute: AstrologerLoginRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ChatsRoute: ChatsRouteWithChildren,
  DetailsRoute: DetailsRoute,
  LiveRoute: LiveRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SeedAstrologersRoute: SeedAstrologersRoute,
  SplashRoute: SplashRoute,
  StoreRoute: StoreRoute,
  WalletRoute: WalletRoute,
  AstrologersIdRoute: AstrologersIdRoute,
  AstrologersIndexRoute: AstrologersIndexRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  CallModeIdRoute: CallModeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
